import React, { useState, useMemo } from "react";
import Select, { SingleValue, StylesConfig } from "react-select";

// Define the CountryOption type
export interface CountryOption {
  label: string;
  value: string;
}

// Define the custom styles for react-select
const customStyles: StylesConfig<CountryOption, false> = {
  control: (provided) => ({
    ...provided,
    width: "120px",
    backgroundColor: "#303054",
    color: "white",
    border: "none",
    boxShadow: "none",
    "&:hover": {
      border: "none",
    },
    "& input": {
      color: "white",
    },
  }),
  menu: (provided) => ({
    ...provided,
    backgroundColor: "#303054",
    color: "white",
  }),
  menuList: (provided) => ({
    ...provided,
    backgroundColor: "#303054",
  }),
  option: (provided, state) => ({
    ...provided,
    backgroundColor: state.isSelected ? "#333" : "#303054",
    color: "white",
    "&:hover": {
      backgroundColor: "#333",
    },
  }),
  placeholder: (provided) => ({
    ...provided,
    color: "white",
  }),
  singleValue: (provided) => ({
    ...provided,
    color: "white",
  }),
};

// Define the props type for the CountrySelector component
type CountrySelectorProps = {
  setCountryCode: (value: any) => void;
  countryCode: SingleValue<CountryOption>;
};

// Define the CountrySelector component
const CountrySelector: React.FC<CountrySelectorProps> = ({
  setCountryCode,
  countryCode,
}) => {
  const options = useMemo(() => {
    return countryPhoneCodes.map((country) => ({
      label: `${country.phoneCode} ${country.code}`,
      value: country.phoneCode,
    }));
  }, []);

  const changeHandler = (selectedOption: SingleValue<CountryOption>) => {
    setCountryCode(selectedOption);
  };

  return (
    <Select
      options={options}
      value={countryCode}
      onChange={changeHandler}
      getOptionLabel={(option) => option.label}
      getOptionValue={(option) => option.value}
      isSearchable
      styles={customStyles}
    />
  );
};

export default CountrySelector;

// utils/countryPhoneCodes.ts
export const countryPhoneCodes = [
  { code: "AF", phoneCode: "+93", label: "Afghanistan" },
  { code: "AL", phoneCode: "+355", label: "Albania" },
  { code: "DZ", phoneCode: "+213", label: "Algeria" },
  { code: "AS", phoneCode: "+1-684", label: "American Samoa" },
  { code: "AD", phoneCode: "+376", label: "Andorra" },
  { code: "AO", phoneCode: "+244", label: "Angola" },
  { code: "AI", phoneCode: "+1-264", label: "Anguilla" },
  { code: "AG", phoneCode: "+1-268", label: "Antigua and Barbuda" },
  { code: "AR", phoneCode: "+54", label: "Argentina" },
  { code: "AM", phoneCode: "+374", label: "Armenia" },
  { code: "AW", phoneCode: "+297", label: "Aruba" },
  { code: "AU", phoneCode: "+61", label: "Australia" },
  { code: "AT", phoneCode: "+43", label: "Austria" },
  { code: "AZ", phoneCode: "+994", label: "Azerbaijan" },
  { code: "BS", phoneCode: "+1-242", label: "Bahamas" },
  { code: "BH", phoneCode: "+973", label: "Bahrain" },
  { code: "BD", phoneCode: "+880", label: "Bangladesh" },
  { code: "BB", phoneCode: "+1-246", label: "Barbados" },
  { code: "BY", phoneCode: "+375", label: "Belarus" },
  { code: "BE", phoneCode: "+32", label: "Belgium" },
  { code: "BZ", phoneCode: "+501", label: "Belize" },
  { code: "BJ", phoneCode: "+229", label: "Benin" },
  { code: "BT", phoneCode: "+975", label: "Bhutan" },
  { code: "BO", phoneCode: "+591", label: "Bolivia" },
  { code: "BA", phoneCode: "+387", label: "Bosnia and Herzegovina" },
  { code: "BW", phoneCode: "+267", label: "Botswana" },
  { code: "BR", phoneCode: "+55", label: "Brazil" },
  { code: "BN", phoneCode: "+673", label: "Brunei" },
  { code: "BG", phoneCode: "+359", label: "Bulgaria" },
  { code: "BF", phoneCode: "+226", label: "Burkina Faso" },
  { code: "BI", phoneCode: "+257", label: "Burundi" },
  { code: "CV", phoneCode: "+238", label: "Cabo Verde" },
  { code: "KH", phoneCode: "+855", label: "Cambodia" },
  { code: "CM", phoneCode: "+237", label: "Cameroon" },
  { code: "CA", phoneCode: "+1", label: "Canada" },
  { code: "KY", phoneCode: "+1-345", label: "Cayman Islands" },
  { code: "CF", phoneCode: "+236", label: "Central African Republic" },
  { code: "TD", phoneCode: "+235", label: "Chad" },
  { code: "CL", phoneCode: "+56", label: "Chile" },
  { code: "CN", phoneCode: "+86", label: "China" },
  { code: "CX", phoneCode: "+61", label: "Christmas Island" },
  { code: "CC", phoneCode: "+61", label: "Cocos (Keeling) Islands" },
  { code: "CO", phoneCode: "+57", label: "Colombia" },
  { code: "KM", phoneCode: "+269", label: "Comoros" },
  { code: "CG", phoneCode: "+242", label: "Congo" },
  { code: "CD", phoneCode: "+243", label: "Congo, Democratic Republic of the" },
  { code: "CK", phoneCode: "+682", label: "Cook Islands" },
  { code: "CR", phoneCode: "+506", label: "Costa Rica" },
  { code: "HR", phoneCode: "+385", label: "Croatia" },
  { code: "CU", phoneCode: "+53", label: "Cuba" },
  { code: "CW", phoneCode: "+599", label: "Curaçao" },
  { code: "CY", phoneCode: "+357", label: "Cyprus" },
  { code: "CZ", phoneCode: "+420", label: "Czech Republic" },
  { code: "DK", phoneCode: "+45", label: "Denmark" },
  { code: "DJ", phoneCode: "+253", label: "Djibouti" },
  { code: "DM", phoneCode: "+1-767", label: "Dominica" },
  { code: "DO", phoneCode: "+1-809", label: "Dominican Republic" },
  { code: "EC", phoneCode: "+593", label: "Ecuador" },
  { code: "EG", phoneCode: "+20", label: "Egypt" },
  { code: "SV", phoneCode: "+503", label: "El Salvador" },
  { code: "GQ", phoneCode: "+240", label: "Equatorial Guinea" },
  { code: "ER", phoneCode: "+291", label: "Eritrea" },
  { code: "EE", phoneCode: "+372", label: "Estonia" },
  { code: "ET", phoneCode: "+251", label: "Ethiopia" },
  { code: "FK", phoneCode: "+500", label: "Falkland Islands" },
  { code: "FO", phoneCode: "+298", label: "Faroe Islands" },
  { code: "FJ", phoneCode: "+679", label: "Fiji" },
  { code: "FI", phoneCode: "+358", label: "Finland" },
  { code: "FR", phoneCode: "+33", label: "France" },
  { code: "GF", phoneCode: "+594", label: "French Guiana" },
  { code: "PF", phoneCode: "+689", label: "French Polynesia" },
  { code: "GA", phoneCode: "+241", label: "Gabon" },
  { code: "GM", phoneCode: "+220", label: "Gambia" },
  { code: "GE", phoneCode: "+995", label: "Georgia" },
  { code: "DE", phoneCode: "+49", label: "Germany" },
  { code: "GH", phoneCode: "+233", label: "Ghana" },
  { code: "GI", phoneCode: "+350", label: "Gibraltar" },
  { code: "GR", phoneCode: "+30", label: "Greece" },
  { code: "GL", phoneCode: "+299", label: "Greenland" },
  { code: "GD", phoneCode: "+1-473", label: "Grenada" },
  { code: "GP", phoneCode: "+590", label: "Guadeloupe" },
  { code: "GU", phoneCode: "+1-671", label: "Guam" },
  { code: "GT", phoneCode: "+502", label: "Guatemala" },
  { code: "GG", phoneCode: "+44-1481", label: "Guernsey" },
  { code: "GN", phoneCode: "+224", label: "Guinea" },
  { code: "GW", phoneCode: "+245", label: "Guinea-Bissau" },
  { code: "GY", phoneCode: "+592", label: "Guyana" },
  { code: "HT", phoneCode: "+509", label: "Haiti" },
  { code: "HM", phoneCode: "+672", label: "Heard Island and McDonald Islands" },
  { code: "VA", phoneCode: "+379", label: "Vatican City" },
  { code: "HN", phoneCode: "+504", label: "Honduras" },
  { code: "HK", phoneCode: "+852", label: "Hong Kong" },
  { code: "HU", phoneCode: "+36", label: "Hungary" },
  { code: "IS", phoneCode: "+354", label: "Iceland" },
  { code: "IN", phoneCode: "+91", label: "India" },
  { code: "ID", phoneCode: "+62", label: "Indonesia" },
  { code: "IR", phoneCode: "+98", label: "Iran" },
  { code: "IQ", phoneCode: "+964", label: "Iraq" },
  { code: "IE", phoneCode: "+353", label: "Ireland" },
  { code: "IM", phoneCode: "+44-1624", label: "Isle of Man" },
  { code: "IL", phoneCode: "+972", label: "Israel" },
  { code: "IT", phoneCode: "+39", label: "Italy" },
  { code: "JE", phoneCode: "+44-1534", label: "Jersey" },
  { code: "JO", phoneCode: "+962", label: "Jordan" },
  { code: "KZ", phoneCode: "+7", label: "Kazakhstan" },
  { code: "KE", phoneCode: "+254", label: "Kenya" },
  { code: "KI", phoneCode: "+686", label: "Kiribati" },
  { code: "KR", phoneCode: "+82", label: "South Korea" },
  { code: "KW", phoneCode: "+965", label: "Kuwait" },
  { code: "KG", phoneCode: "+996", label: "Kyrgyzstan" },
  { code: "LA", phoneCode: "+856", label: "Laos" },
  { code: "LV", phoneCode: "+371", label: "Latvia" },
  { code: "LB", phoneCode: "+961", label: "Lebanon" },
  { code: "LS", phoneCode: "+266", label: "Lesotho" },
  { code: "LR", phoneCode: "+231", label: "Liberia" },
  { code: "LY", phoneCode: "+218", label: "Libya" },
  { code: "LI", phoneCode: "+423", label: "Liechtenstein" },
  { code: "LT", phoneCode: "+370", label: "Lithuania" },
  { code: "LU", phoneCode: "+352", label: "Luxembourg" },
  { code: "MO", phoneCode: "+853", label: "Macau" },
  { code: "MK", phoneCode: "+389", label: "North Macedonia" },
  { code: "MG", phoneCode: "+261", label: "Madagascar" },
  { code: "MW", phoneCode: "+265", label: "Malawi" },
  { code: "MY", phoneCode: "+60", label: "Malaysia" },
  { code: "MV", phoneCode: "+960", label: "Maldives" },
  { code: "ML", phoneCode: "+223", label: "Mali" },
  { code: "MT", phoneCode: "+356", label: "Malta" },
  { code: "MH", phoneCode: "+692", label: "Marshall Islands" },
  { code: "MQ", phoneCode: "+596", label: "Martinique" },
  { code: "MR", phoneCode: "+222", label: "Mauritania" },
  { code: "MU", phoneCode: "+230", label: "Mauritius" },
  { code: "YT", phoneCode: "+262", label: "Mayotte" },
  { code: "MX", phoneCode: "+52", label: "Mexico" },
  { code: "FM", phoneCode: "+691", label: "Micronesia" },
  { code: "MD", phoneCode: "+373", label: "Moldova" },
  { code: "MC", phoneCode: "+377", label: "Monaco" },
  { code: "MN", phoneCode: "+976", label: "Mongolia" },
  { code: "ME", phoneCode: "+382", label: "Montenegro" },
  { code: "MS", phoneCode: "+1-664", label: "Montserrat" },
  { code: "MA", phoneCode: "+212", label: "Morocco" },
  { code: "MZ", phoneCode: "+258", label: "Mozambique" },
  { code: "MM", phoneCode: "+95", label: "Myanmar" },
  { code: "NA", phoneCode: "+264", label: "Namibia" },
  { code: "NR", phoneCode: "+674", label: "Nauru" },
  { code: "NP", phoneCode: "+977", label: "Nepal" },
  { code: "NL", phoneCode: "+31", label: "Netherlands" },
  { code: "NC", phoneCode: "+687", label: "New Caledonia" },
  { code: "NZ", phoneCode: "+64", label: "New Zealand" },
  { code: "NI", phoneCode: "+505", label: "Nicaragua" },
  { code: "NE", phoneCode: "+227", label: "Niger" },
  { code: "NG", phoneCode: "+234", label: "Nigeria" },
  { code: "NU", phoneCode: "+683", label: "Niue" },
  { code: "NF", phoneCode: "+672", label: "Norfolk Island" },
  { code: "MP", phoneCode: "+1-670", label: "Northern Mariana Islands" },
  { code: "NO", phoneCode: "+47", label: "Norway" },
  { code: "OM", phoneCode: "+968", label: "Oman" },
  { code: "PK", phoneCode: "+92", label: "Pakistan" },
  { code: "PW", phoneCode: "+680", label: "Palau" },
  { code: "PA", phoneCode: "+507", label: "Panama" },
  { code: "PG", phoneCode: "+675", label: "Papua New Guinea" },
  { code: "PY", phoneCode: "+595", label: "Paraguay" },
  { code: "PE", phoneCode: "+51", label: "Peru" },
  { code: "PH", phoneCode: "+63", label: "Philippines" },
  { code: "PN", phoneCode: "+870", label: "Pitcairn Islands" },
  { code: "PL", phoneCode: "+48", label: "Poland" },
  { code: "PT", phoneCode: "+351", label: "Portugal" },
  { code: "PR", phoneCode: "+1-787", label: "Puerto Rico" },
  { code: "QA", phoneCode: "+974", label: "Qatar" },
  { code: "RE", phoneCode: "+262", label: "Réunion" },
  { code: "RO", phoneCode: "+40", label: "Romania" },
  { code: "RU", phoneCode: "+7", label: "Russia" },
  { code: "RW", phoneCode: "+250", label: "Rwanda" },
  { code: "BL", phoneCode: "+590", label: "Saint Barthélemy" },
  { code: "SH", phoneCode: "+290", label: "Saint Helena" },
  { code: "KN", phoneCode: "+1-869", label: "Saint Kitts and Nevis" },
  { code: "LC", phoneCode: "+1-758", label: "Saint Lucia" },
  { code: "MF", phoneCode: "+590", label: "Saint Martin" },
  { code: "PM", phoneCode: "+508", label: "Saint Pierre and Miquelon" },
  {
    code: "VC",
    phoneCode: "+1-784",
    label: "Saint Vincent and the Grenadines",
  },
  { code: "WS", phoneCode: "+685", label: "Samoa" },
  { code: "SM", phoneCode: "+378", label: "San Marino" },
  { code: "ST", phoneCode: "+239", label: "São Tomé and Príncipe" },
  { code: "SA", phoneCode: "+966", label: "Saudi Arabia" },
  { code: "SN", phoneCode: "+221", label: "Senegal" },
  { code: "RS", phoneCode: "+381", label: "Serbia" },
  { code: "SC", phoneCode: "+248", label: "Seychelles" },
  { code: "SL", phoneCode: "+232", label: "Sierra Leone" },
  { code: "SG", phoneCode: "+65", label: "Singapore" },
  { code: "SX", phoneCode: "+1-721", label: "Sint Maarten" },
  { code: "SK", phoneCode: "+421", label: "Slovakia" },
  { code: "SI", phoneCode: "+386", label: "Slovenia" },
  { code: "SB", phoneCode: "+677", label: "Solomon Islands" },
  { code: "SO", phoneCode: "+252", label: "Somalia" },
  { code: "ZA", phoneCode: "+27", label: "South Africa" },
  { code: "SS", phoneCode: "+211", label: "South Sudan" },
  { code: "ES", phoneCode: "+34", label: "Spain" },
  { code: "LK", phoneCode: "+94", label: "Sri Lanka" },
  { code: "SD", phoneCode: "+249", label: "Sudan" },
  { code: "SR", phoneCode: "+597", label: "Suriname" },
  { code: "SJ", phoneCode: "+47", label: "Svalbard and Jan Mayen" },
  { code: "SZ", phoneCode: "+268", label: "Eswatini" },
  { code: "SE", phoneCode: "+46", label: "Sweden" },
  { code: "CH", phoneCode: "+41", label: "Switzerland" },
  { code: "SY", phoneCode: "+963", label: "Syria" },
  { code: "TW", phoneCode: "+886", label: "Taiwan" },
  { code: "TJ", phoneCode: "+992", label: "Tajikistan" },
  { code: "TZ", phoneCode: "+255", label: "Tanzania" },
  { code: "TH", phoneCode: "+66", label: "Thailand" },
  { code: "TL", phoneCode: "+670", label: "Timor-Leste" },
  { code: "TG", phoneCode: "+228", label: "Togo" },
  { code: "TK", phoneCode: "+690", label: "Tokelau" },
  { code: "TO", phoneCode: "+676", label: "Tonga" },
  { code: "TT", phoneCode: "+1-868", label: "Trinidad and Tobago" },
  { code: "TN", phoneCode: "+216", label: "Tunisia" },
  { code: "TR", phoneCode: "+90", label: "Turkey" },
  { code: "TM", phoneCode: "+993", label: "Turkmenistan" },
  { code: "TC", phoneCode: "+1-649", label: "Turks and Caicos Islands" },
  { code: "TV", phoneCode: "+688", label: "Tuvalu" },
  { code: "UG", phoneCode: "+256", label: "Uganda" },
  { code: "UA", phoneCode: "+380", label: "Ukraine" },
  { code: "AE", phoneCode: "+971", label: "United Arab Emirates" },
  { code: "GB", phoneCode: "+44", label: "United Kingdom" },
  { code: "US", phoneCode: "+1", label: "United States" },
  { code: "UY", phoneCode: "+598", label: "Uruguay" },
  { code: "UZ", phoneCode: "+998", label: "Uzbekistan" },
  { code: "VU", phoneCode: "+678", label: "Vanuatu" },
  { code: "VE", phoneCode: "+58", label: "Venezuela" },
  { code: "VN", phoneCode: "+84", label: "Vietnam" },
  { code: "WF", phoneCode: "+681", label: "Wallis and Futuna" },
  { code: "EH", phoneCode: "+212", label: "Western Sahara" },
  { code: "YE", phoneCode: "+967", label: "Yemen" },
  { code: "ZM", phoneCode: "+260", label: "Zambia" },
  { code: "ZW", phoneCode: "+263", label: "Zimbabwe" },
];
